// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cFast

#ifndef UI_MUSIC_PLAYER_H
#define UI_MUSIC_PLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music_Player
extern void ui_Music_Player_screen_init(void);
extern void ui_Music_Player_screen_destroy(void);
extern lv_obj_t * ui_Music_Player;
extern lv_obj_t * ui_Music_Title1;
extern lv_obj_t * ui_Play_btn;
extern lv_obj_t * ui_Play;
extern lv_obj_t * ui_Album;
extern lv_obj_t * ui_Backward;
extern lv_obj_t * ui_Forward;
extern lv_obj_t * ui_soundLvl;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

