// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cFast

#include "../ui.h"

lv_obj_t * ui_Music_Player = NULL;
lv_obj_t * ui_Music_Title1 = NULL;
lv_obj_t * ui_Play_btn = NULL;
lv_obj_t * ui_Play = NULL;
lv_obj_t * ui_Album = NULL;
lv_obj_t * ui_Backward = NULL;
lv_obj_t * ui_Forward = NULL;
lv_obj_t * ui_soundLvl = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Music_Player_screen_init(void)
{
    ui_Music_Player = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Music_Player, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Music_Player, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music_Player, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Music_Player, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Music_Player, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Music_Title1 = lv_label_create(ui_Music_Player);
    lv_obj_set_width(ui_Music_Title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Music_Title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Music_Title1, 0);
    lv_obj_set_y(ui_Music_Title1, 25);
    lv_obj_set_align(ui_Music_Title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Music_Title1, "Wood and forest");
    lv_obj_set_style_text_color(ui_Music_Title1, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Music_Title1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Music_Title1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Play_btn = lv_obj_create(ui_Music_Player);
    lv_obj_set_width(ui_Play_btn, 60);
    lv_obj_set_height(ui_Play_btn, 60);
    lv_obj_set_x(ui_Play_btn, 0);
    lv_obj_set_y(ui_Play_btn, -12);
    lv_obj_set_align(ui_Play_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Play_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Play_btn, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Play_btn, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Play_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Play_btn, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Play_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Play_btn, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Play_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Play_btn, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Play_btn, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Play_btn, lv_color_hex(0x515EB5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Play_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Play = lv_img_create(ui_Play_btn);
    lv_img_set_src(ui_Play, &ui_img_play_png);
    lv_obj_set_width(ui_Play, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Play, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Play, -1);
    lv_obj_set_y(ui_Play, 0);
    lv_obj_set_align(ui_Play, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Play, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Play, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Album = lv_img_create(ui_Music_Player);
    lv_img_set_src(ui_Album, &ui_img_album_png);
    lv_obj_set_width(ui_Album, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Album, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Album, 0);
    lv_obj_set_y(ui_Album, 20);
    lv_obj_set_align(ui_Album, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Album, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Album, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Album, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Album, lv_color_hex(0xD5D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Album, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Album, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Album, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Album, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Album, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Backward = lv_img_create(ui_Music_Player);
    lv_img_set_src(ui_Backward, &ui_img_backward_png);
    lv_obj_set_width(ui_Backward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Backward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Backward, 30);
    lv_obj_set_y(ui_Backward, -28);
    lv_obj_set_align(ui_Backward, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Backward, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Backward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Backward, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Backward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Backward, lv_color_hex(0x515EB5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Backward, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Forward = lv_img_create(ui_Music_Player);
    lv_img_set_src(ui_Forward, &ui_img_forward_png);
    lv_obj_set_width(ui_Forward, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Forward, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Forward, -30);
    lv_obj_set_y(ui_Forward, -30);
    lv_obj_set_align(ui_Forward, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Forward, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Forward, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_Forward, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_Forward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor(ui_Forward, lv_color_hex(0x515EB5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_img_recolor_opa(ui_Forward, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_soundLvl = lv_img_create(ui_Music_Player);
    lv_img_set_src(ui_soundLvl, &ui_img_1672721641);
    lv_obj_set_width(ui_soundLvl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_soundLvl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_soundLvl, -104);
    lv_obj_set_y(ui_soundLvl, -100);
    lv_obj_set_align(ui_soundLvl, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_soundLvl, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_soundLvl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Music_Player);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -79);
    lv_obj_set_y(ui_Label1, -100);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "100");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Music_Player_screen_destroy(void)
{
    if(ui_Music_Player) lv_obj_del(ui_Music_Player);

    // NULL screen variables
    ui_Music_Player = NULL;
    ui_Music_Title1 = NULL;
    ui_Play_btn = NULL;
    ui_Play = NULL;
    ui_Album = NULL;
    ui_Backward = NULL;
    ui_Forward = NULL;
    ui_soundLvl = NULL;
    ui_Label1 = NULL;

}
