// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cFast

#include "../ui.h"

lv_obj_t * ui_Splash = NULL;
lv_obj_t * ui_Audio_Player1 = NULL;
lv_obj_t * ui_C_Fast1 = NULL;
lv_obj_t * ui_SLS_Logo = NULL;
// event funtions

// build funtions

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Splash, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Splash, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Audio_Player1 = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Audio_Player1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Audio_Player1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Audio_Player1, 0);
    lv_obj_set_y(ui_Audio_Player1, 75);
    lv_obj_set_align(ui_Audio_Player1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Audio_Player1, "Audio Player");
    lv_obj_set_style_text_color(ui_Audio_Player1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Audio_Player1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Audio_Player1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_C_Fast1 = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_C_Fast1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_C_Fast1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_C_Fast1, 0);
    lv_obj_set_y(ui_C_Fast1, 50);
    lv_obj_set_align(ui_C_Fast1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_C_Fast1, "C Fast");
    lv_obj_set_style_text_color(ui_C_Fast1, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_C_Fast1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_C_Fast1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLS_Logo = lv_img_create(ui_Splash);
    lv_img_set_src(ui_SLS_Logo, &ui_img_sls_logo_png);
    lv_obj_set_width(ui_SLS_Logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLS_Logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SLS_Logo, 0);
    lv_obj_set_y(ui_SLS_Logo, -50);
    lv_obj_set_align(ui_SLS_Logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SLS_Logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SLS_Logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Splash_screen_destroy(void)
{
    if(ui_Splash) lv_obj_del(ui_Splash);

    // NULL screen variables
    ui_Splash = NULL;
    ui_Audio_Player1 = NULL;
    ui_C_Fast1 = NULL;
    ui_SLS_Logo = NULL;

}
