// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: cFast

#ifndef _CFAST_UI_H
#define _CFAST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Splash.h"
#include "screens/ui_Music_Player.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_1672721641);    // assets/sound-icon-speaker-music-volume-260nw-1069384451.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
